#!/usr/bin/env python3
"""Independent cleanliness audit of the rebuilt deck: real TeX-leak test +
C0 / banned-phrase / math-correctness spot checks."""
import re, glob, hashlib, os

ROOT = os.path.dirname(os.path.abspath(__file__))
CARDS = sorted(g for g in glob.glob(os.path.join(ROOT, "*.html")) if os.path.basename(g) != "index.html")
GUIDE = "/root/agent-artifacts/workspace/revision_pipeline/lessons/2026-07-12_harry_differentiation_trig/guide/harry_2026-07-12_differentiation_trig_revision_guide.tex"

TEX_CMDS = r"\\(tfrac|frac|sin|cos|sqrt|alpha|beta|pi|ln|Rightarrow|infty|cosec|sec|cot|tan|operatorname)"

def visible_text_outside_math(s):
    s = re.sub(r"<script.*?</script>", "", s, flags=re.S)
    # keep only text outside \(...\) and \[...\]
    parts = re.split(r"\\\[.*?\\\]|\\\(.*?\\\)", s, flags=re.S)
    out = []
    for seg in parts:
        if seg is None:
            continue
        txt = re.sub(r"<[^>]+>", " ", seg)
        out.append(txt)
    return " ".join(out)

leak = False
for c in CARDS:
    s = open(c, encoding="utf-8").read()
    vt = visible_text_outside_math(s)
    hits = re.findall(TEX_CMDS, vt)
    if hits:
        print("REAL TEX LEAK in", os.path.basename(c), ":", set(hits))
        leak = True
print("REAL TEX LEAK:", leak)

# C0 control bytes
c0 = False
for c in CARDS:
    s = open(c, encoding="utf-8").read()
    bad = [hex(ord(ch)) for ch in s if ord(ch) < 32 and ch != "\n"]
    if bad:
        print("C0 in", os.path.basename(c), bad); c0 = True
print("C0 present:", c0)

# banned phrases
banned = False
for c in CARDS:
    s = open(c, encoding="utf-8").read()
    if re.search(r"html2canvas|Generated by|Reveal this box|Let me reconsider", s, re.I):
        print("BANNED in", os.path.basename(c)); banned = True
print("Banned phrases:", banned)

# Math-correctness spot checks: key final answers must appear verbatim.
guide = open(GUIDE, encoding="utf-8").read()
def has(path, *subs):
    s = open(path, encoding="utf-8").read()
    return all(sub in s for sub in subs)

checks = {
    "Q1 vertex": has(os.path.join(ROOT,"P3_Jun2024_Q1.html"), r"P=(5,\,10)"),
    "Q1 x<5/2": has(os.path.join(ROOT,"P3_Jun2024_Q1.html"), r"x=\tfrac52", r"x&lt;\tfrac52"),
    "Q1 image (7,30)": has(os.path.join(ROOT,"P3_Jun2024_Q1.html"), r"P'=(7,\,30)"),
    "Q2 A2,B-1,C6": r"A=2,\ B=-1,\ C=6" in open(os.path.join(ROOT,"P3_Jun2024_Q2.html"),encoding="utf-8").read(),
    "Q2 44+6ln3": r"44+6\ln 3" in open(os.path.join(ROOT,"P3_Jun2024_Q2.html"),encoding="utf-8").read(),
    "Q4 a4b2c-1": r"a=4,\ b=2,\ c=-1" in open(os.path.join(ROOT,"P3_Jun2024_Q4.html"),encoding="utf-8").read(),
    "Q4 R=2sqrt5": r"R=\sqrt{20}=2\sqrt5" in open(os.path.join(ROOT,"P3_Jun2024_Q4.html"),encoding="utf-8").read(),
    "Q4 max 2sqrt5-1": r"f_{\max}=2\sqrt5-1" in open(os.path.join(ROOT,"P3_Jun2024_Q4.html"),encoding="utf-8").read(),
    "Q4 x~3.69": r"x\approx3.69" in open(os.path.join(ROOT,"P3_Jun2024_Q4.html"),encoding="utf-8").read(),
}
for k,v in checks.items():
    print(f"  math[{k}] = {v}")
print("ALL MATH OK:", all(checks.values()))

# Guide untouched
for f in ["guide/harry_2026-07-12_differentiation_trig_revision_guide.tex",
          "guide/harry_2026-07-12_differentiation_trig_revision_guide.pdf"]:
    p = os.path.join(os.path.dirname(ROOT), f)
    print("guide", f, "exists" if os.path.exists(p) else "MISSING")

result = (not leak) and (not c0) and (not banned) and all(checks.values())
print("\n=== INDEPENDENT AUDIT:", "PASS" if result else "FAIL", "===")
