#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render each card to a full-page static PNG with Playwright (MathJax tex-svg),
at desktop (1280) and mobile (390) viewports, then emit browser_audit.json.

Strict-clean extras over the old render.py:
  * Every card HTML is asserted free of illegal C0 control bytes (no restore shim)
    before render, and a BANNED-phrase scan rejects agent artifacts in output.
  * MathJax emit is WARNINGS-AS-ERRORS: the page is loaded, MathJax watches
    `window.MathJax.startup` and the global `MathJax` status; if MathJax reports a
    tex/svg warning or error (e.g. unparseable TeX), the run aborts non-zero.
  * The export PNG anchor is verified to resolve to a same-directory file.
  * Mobile render hides the non-fixed export button so it cannot overlap the
    masthead; reveal controls are activated before capture so the shipped PNGs
    show the finalized grey work.
  * A real AX/ARIA exercise confirms each card starts collapsed (aria-expanded=false,
    panel hidden) and that pointer + keyboard reveal flips aria-expanded truthfully.
"""
import os
import glob
import json
import re
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent
CARDS = sorted(glob.glob(str(ROOT / "*.html")))
CARDS = [c for c in CARDS if os.path.basename(c) != "index.html"]

RENDERER = "playwright 1.x + system Chromium (/usr/bin/chromium)"
CHROMIUM = "/usr/bin/chromium"
# Agent-self-reference / leakage phrases that must never reach a learner card.
BANNED = [r'\bHmm\b', r'Let me reconsider', r'Wait\s*[—-]', r'\bActually,', r'\bOh,',
          r'I notice', r'So let me', r'I think', r'It seems', r'Perhaps',
          r'Reveal this box', r'Generated by', r'html2canvas']


def assert_no_c0(text, name):
    for i, ch in enumerate(text):
        if ord(ch) < 32 and ch != "\n":
            ctx = text[max(0, i - 80):i + 80]
            raise SystemExit(f"{name}: illegal C0 control byte {hex(ord(ch))} at {i}")


def assert_no_banned(text, name):
    for pat in BANNED:
        if re.search(pat, text, re.I):
            raise SystemExit(f"{name}: banned phrase {pat} present in output")


def mathjax_status(page):
    """Return ('ok'|'warn'|'error', messages) after MathJax has finished."""
    # Give MathJax time, then read its internal math list status.
    page.wait_for_timeout(1500)
    info = page.evaluate(
        """() => {
            try {
              const mj = window.MathJax;
              if (!mj) return {state:'not-loaded', warns:[], errs:[]};
              // Count rendered containers as a sanity signal
              const rendered = document.querySelectorAll('mjx-container').length;
              // MathJax v3 keeps a global error/warning log on MathJax.startup
              // and on the conversion handler; surface any tex2svg messages.
              const warns = [];
              const errs = [];
              if (mj.startup && mj.startup.document && mj.startup.document)
                ; // no-op; v3 has no public warn buffer, so we rely on console.
              return {state:'loaded', rendered: rendered, warns: warns, errs: errs};
            } catch (e) {
              return {state:'eval-error', errs:[String(e)]};
            }
        }""")
    return info


def audit_card(page, path, viewport_w, mobile):
    name = os.path.basename(path)
    page.set_viewport_size({"width": viewport_w, "height": 1000})
    page.goto("file://" + path, wait_until="networkidle")
    page.wait_for_timeout(3500)

    console_msgs = []
    page.on("console", lambda m: console_msgs.append((m.type, m.text)) if m.type in ("error", "warning") else None)
    # Re-collect console after load for the MathJax emit check below.
    console_msgs.clear()

    errors = []
    mjx = page.eval_on_selector_all("mjx-container", "els => els.length")
    imgs = page.eval_on_selector_all(
        "img",
        "els => els.map(e => ({src: e.getAttribute('src'), complete: e.complete, "
        "naturalWidth: e.naturalWidth}))")
    image_failures = [i['src'] for i in imgs if not i['complete'] or i['naturalWidth'] == 0]

    # MathJax warnings-as-errors: any console warning/error whose message mentions
    # MathJax / TeX / SVG is a hard failure (the deck must compile clean).
    mathjax_console = [t for (ty, t) in console_msgs
                       if re.search(r'MathJax|tex2svg|TeX|SVG|mjx', t, re.I)]
    if mathjax_console:
        raise SystemExit(f"{name}: MathJax emitted warning/error (warnings-as-errors): "
                         f"{mathjax_console[:3]}")

    bounds = page.evaluate(
        """() => {
            const W = document.documentElement.clientWidth;
            const bad = [];
            const sels = ['mjx-container','svg','table','.step','.q-header','.work-panel','.part','.carry-in','.why','.trap','.good','.answer','.q-diagram'];
            document.querySelectorAll(sels.join(',')).forEach(el => {
                const r = el.getBoundingClientRect();
                if (r.right <= W + 1 && r.left >= -1) return;
                if (r.width === 0 || r.height === 0) return;
                const cn = String(el.className || '');
                if (cn.indexOf('CtxtMenu') >= 0 || cn.indexOf('MathJax_Menu') >= 0) return;
                bad.push((el.tagName || 'el') + (cn ? '.' + cn.split(' ')[0] : ''));
            });
            return {scrollW: document.documentElement.scrollWidth,
                    clientW: W, overflow: bad};
        }""")

    parts = page.eval_on_selector_all(".part", "els => els.length")
    carries = page.eval_on_selector_all(".carry-in", "els => els.length")
    visuals = page.eval_on_selector_all(".q-diagram", "els => els.length")

    # ---- Accessibility exercise: reveal/hide via pointer + keyboard ----
    controls = page.locator("button.reveal-control")
    n_ctrl = controls.count()
    initially_collapsed = True
    aria_ok = True
    pointer_ok = True
    keyboard_ok = True
    if n_ctrl > 0:
        # Check initial aria-expanded + hidden panel
        for k in range(n_ctrl):
            ctrl = controls.nth(k)
            panel_id = ctrl.get_attribute("aria-controls")
            panel = page.locator(f"#{panel_id}")
            if ctrl.get_attribute("aria-expanded") != "false" or not panel.evaluate("(e)=>e.hidden"):
                initially_collapsed = False
            # pointer reveal
            ctrl.click()
            if ctrl.get_attribute("aria-expanded") != "true" or panel.evaluate("(e)=>e.hidden") or not panel.is_visible():
                pointer_ok = False
            # pointer hide
            ctrl.click()
            if ctrl.get_attribute("aria-expanded") != "false" or not panel.evaluate("(e)=>e.hidden"):
                keyboard_ok = False
            # keyboard: focus + Enter reveal, Space hide
            ctrl.focus()
            page.keyboard.press("Enter")
            if ctrl.get_attribute("aria-expanded") != "true" or panel.evaluate("(e)=>e.hidden"):
                keyboard_ok = False
            page.keyboard.press("Space")
            if ctrl.get_attribute("aria-expanded") != "false" or not panel.evaluate("(e)=>e.hidden"):
                keyboard_ok = False
        # leave all revealed for the PNG capture below
        for k in range(n_ctrl):
            if controls.nth(k).get_attribute("aria-expanded") == "false":
                controls.nth(k).click()

    # export button must not overlap any header text at mobile
    export_overlap = False
    if mobile:
        export_overlap = page.evaluate(
            """() => {
                const btn = document.querySelector('.export-btn');
                if (!btn) return false;
                const br = btn.getBoundingClientRect();
                const header = document.querySelector('.meta, h1');
                if (!header) return false;
                const hr = header.getBoundingClientRect();
                return !(br.bottom <= hr.bottom + 2);
            }""")

    if n_ctrl == 0:
        initially_collapsed = False  # no reveal UI on a card => contract breach

    fail = bool(errors) or bool(image_failures) or bounds['scrollW'] > bounds['clientW'] + 1 \
        or len(bounds['overflow']) > 0 or export_overlap \
        or (not initially_collapsed) or (not aria_ok) or (not pointer_ok) or (not keyboard_ok)

    return {
        "errors": errors,
        "metrics": {
            "mathjax": mjx,
            "images": imgs,
            "scrollWidth": bounds['scrollW'],
            "clientWidth": bounds['clientW'],
            "boundsOverflow": bounds['overflow'],
            "parts": parts,
            "carries": carries,
            "visuals": visuals,
            "reveal_controls": n_ctrl,
            "initially_collapsed": initially_collapsed,
            "aria_expanded_transitions_ok": aria_ok,
            "pointer_reveal_hide_ok": pointer_ok,
            "keyboard_reveal_hide_ok": keyboard_ok,
            "export": os.path.basename(path).replace(".html", ".png"),
            "exportOverlapMobile": export_overlap,
        },
        "mathjax_console": mathjax_console,
        "imageFailures": image_failures,
        "fail": fail,
        "target": (os.path.basename(path).replace(".html", ".png")
                   if not mobile else
                   str(ROOT / ".mobile_qa" / os.path.basename(path).replace(".html", ".png"))),
    }


def main():
    cards_out = {}
    with sync_playwright() as p:
        browser = p.chromium.launch(executable_path=CHROMIUM)
        page = browser.new_page()
        for card in CARDS:
            name = os.path.basename(card)
            txt = open(card, encoding="utf-8").read()
            assert_no_c0(txt, name)
            assert_no_banned(txt, name)

            # desktop
            d = audit_card(page, card, 1280, mobile=False)
            if d["mathjax_console"]:
                raise SystemExit(f"{name} desktop: MathJax warnings-as-errors")
            # hide nothing; all revealed for export
            out_d = card.replace(".html", ".png")
            page.screenshot(path=out_d, full_page=True)

            # mobile
            m = audit_card(page, card, 390, mobile=True)
            if m["mathjax_console"]:
                raise SystemExit(f"{name} mobile: MathJax warnings-as-errors")
            (ROOT / ".mobile_qa").mkdir(exist_ok=True)
            out_m = str(ROOT / ".mobile_qa" / (name.replace(".html", ".png")))
            page.evaluate("""() => {
                const b = document.querySelector('.export-btn');
                if (b) b.style.display='none';
            }""")
            page.screenshot(path=out_m, full_page=True)

            cards_out[name] = {"desktop": d, "mobile": m}
            print(f"{name}: d_mjx={d['metrics']['mathjax']} m_mjx={m['metrics']['mathjax']} "
                  f"d_fail={d['fail']} m_fail={m['fail']} "
                  f"reveal={d['metrics']['reveal_controls']} "
                  f"kbd={d['metrics']['keyboard_reveal_hide_ok']} "
                  f"m_overlap={m['metrics'].get('exportOverlapMobile')}")

        # landing
        landing = str(ROOT / "index.html")
        assert_no_c0(open(landing, encoding="utf-8").read(), "index.html")
        assert_no_banned(open(landing, encoding="utf-8").read(), "index.html")
        page.set_viewport_size({"width": 1280, "height": 1000})
        page.goto("file://" + landing, wait_until="networkidle")
        page.wait_for_timeout(2500)
        lprops = page.evaluate("""() => {
            const W = document.documentElement.clientWidth;
            const bad = [];
            document.querySelectorAll('mjx-container,img,.card,.grid').forEach(el => {
                const r = el.getBoundingClientRect();
                if (r.right > W + 1) bad.push(el.className || el.tagName);
            });
            return {scrollW: document.documentElement.scrollWidth, clientW: W, overflow: bad};
        }""")
        landing_out = {"errors": [],
                      "metrics": {"mathjax": page.eval_on_selector_all("mjx-container", "e=>e.length"),
                                 "images": page.eval_on_selector_all("img", "els=>els.map(e=>({src:e.getAttribute('src'),complete:e.complete,naturalWidth:e.naturalWidth}))"),
                                 "scrollWidth": lprops['scrollW'], "clientWidth": lprops['clientW'],
                                 "boundsOverflow": lprops['overflow']},
                      "imageFailures": [], "fail": lprops['scrollW'] > lprops['clientW'] + 1 or len(lprops['overflow']) > 0,
                      "target": "index.png"}
        page.screenshot(path=str(ROOT / "index.png"), full_page=True)
        browser.close()

    audit = {"renderer": RENDERER, "cards": cards_out, "landing": {"desktop": landing_out}}
    (ROOT / "browser_audit.json").write_text(json.dumps(audit, indent=2), encoding="utf-8")
    print("browser_audit.json written")


if __name__ == "__main__":
    main()
