#!/usr/bin/env python3
"""Final deterministic self-QA + manifest. Does not perform independent review."""
from __future__ import annotations
import hashlib, json, re
from pathlib import Path
from PIL import Image, ImageStat

ROOT=Path(__file__).resolve().parent
GUIDE=Path("/root/agent-artifacts/workspace/revision_pipeline/lessons/2026-07-11_harry_p3_esat/guide/harry_2026-07-11_p3_esat_revision_guide.tex")
CARDS=["ESAT_warmup","P3_Oct2025_Q2","P3_Oct2025_Q3","P3_Oct2025_Q4","P3_Oct2025_Q5"]
BANNED=["hmm","let me reconsider","wait —","actually,","oh,","i notice","so let me","i think","it seems","perhaps","reveal this box","generated by","this card"]

def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()

def main():
    checks=[]
    def add(name, passed, detail): checks.append({"name":name,"passed":bool(passed),"detail":detail})
    htmls=[ROOT/f"{s}.html" for s in CARDS]
    all_text=[*htmls,ROOT/"index.html",ROOT/"build_deck.py",ROOT/"render_and_audit.py",Path(__file__)]
    # Frozen external source provenance.
    add("guide_provenance_exists",GUIDE.exists(),str(GUIDE))
    add("exact_card_count",len(htmls)==5,f"{len(htmls)} card HTML files; intended source-bounded scope is ESAT + P3 Q2–Q5")
    add("landing_tile_count",(ROOT/"index.html").read_text().count('class="tile"')==5,"index.html declares five card tiles")
    # Size, renderer, header/part/carry/export and controls.
    for p,slug in zip(htmls,CARDS):
        text=p.read_text(encoding="utf-8")
        add(f"{slug}:depth",p.stat().st_size>=10000,f"{p.stat().st_size} bytes")
        add(f"{slug}:mathjax_svg",'mathjax-tex-svg.js' in text and 'tex-mml-chtml' not in text,"tex-svg present; CHTML absent")
        add(f"{slug}:literal_export",f'href="{slug}.png" target="_blank"' in text and 'onclick=' not in text and 'exportPNG' not in text,"literal same-directory PNG anchor")
        add(f"{slug}:question_header",'<section class="q-header">' in text and 'marks' in text,"standalone header and visible marks")
        parts=text.count('class="part"'); carries=text.count('class="carry-in"')
        add(f"{slug}:parts_and_carryins",parts>0 and carries>=parts,f"{parts} exam parts; {carries} outside-mask carry-ins (including recall strip)")
        add(f"{slug}:maskable_work",text.count('data-maskable="true"')>=parts,f"{text.count('data-maskable=\"true\"')} grey maskable panels")
        add(f"{slug}:visual_anchor",text.count('class="q-diagram"')>=1,"at least one compact teaching visual")
    # Content scans exclude build/report machinery; only learner-facing HTML.
    learner="\n".join(p.read_text(encoding="utf-8") for p in [*htmls,ROOT/"index.html"]).lower()
    banned_hits=[term for term in BANNED if term in learner]
    add("banned_draft_meta_phrases",not banned_hits,", ".join(banned_hits) if banned_hits else "0 hits")
    placeholder_hits=[x for x in ["todo","lorem ipsum","specific value or expression","[insert","tbc"] if x in learner]
    add("no_placeholders",not placeholder_hits,", ".join(placeholder_hits) if placeholder_hits else "0 hits")
    control=[]
    for p in all_text:
        raw=p.read_text(encoding="utf-8")
        bad=[(i,ord(c)) for i,c in enumerate(raw) if ord(c)<32 and c not in "\n\r\t"]
        if bad: control.append({"file":p.name,"bad":bad[:4]})
    add("no_illegal_control_characters",not control,json.dumps(control) if control else "0 files")
    # Privacy scan over final text artifacts.
    privacy_patterns={"email":r"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}","api_key":r"(?:sk-|xox[baprs]-)[A-Za-z0-9_-]{12,}","password":r"(?i)(?:password|secret)\s*[:=]\s*\S+","credit_card":r"\b(?:\d[ -]*?){13,16}\b"}
    privacy_hits=[]
    aggregate="\n".join(p.read_text(encoding="utf-8",errors="replace") for p in all_text)
    for label,pattern in privacy_patterns.items():
        if re.search(pattern,aggregate): privacy_hits.append(label)
    add("privacy_scan",not privacy_hits,", ".join(privacy_hits) if privacy_hits else "no emails, tokens, passwords, or card-like numbers")
    # Link destinations from their own containing directory.
    missing=[]; seen=0
    for p in [ROOT/"index.html",*htmls]:
        for val in re.findall(r'(?:href|src)="([^"]+)"',p.read_text(encoding="utf-8")):
            if val.startswith(("http:","https:","data:","#")): continue
            seen+=1; dest=(p.parent/val).resolve()
            if not dest.exists() or not str(dest).startswith(str(ROOT.resolve())): missing.append(f"{p.name}:{val}")
    add("local_relative_assets",not missing,f"{seen} destinations checked; {len(missing)} missing" + (" — "+"; ".join(missing) if missing else ""))
    # PNG integrity / basic visual information.
    pngs=[ROOT/f"{s}.png" for s in CARDS]+[ROOT/"contact_sheet_desktop.png",ROOT/"contact_sheet_mobile.png"]+list((ROOT/"diagrams").glob("*.png"))
    png_bad=[]; png_meta=[]
    for p in sorted(pngs):
        try:
            im=Image.open(p); im.verify(); im=Image.open(p).convert("RGB"); stat=ImageStat.Stat(im)
            variance=sum(stat.var)/len(stat.var); ok=p.stat().st_size>10000 and im.width>200 and im.height>100 and variance>10
            png_meta.append({"file":str(p.relative_to(ROOT)),"width":im.width,"height":im.height,"bytes":p.stat().st_size,"variance":round(variance,2),"ok":ok})
            if not ok: png_bad.append(p.name)
        except Exception as e: png_bad.append(f"{p.name}:{e}")
    add("png_integrity_dimensions_variance",not png_bad,f"{len(png_meta)} PNGs checked; failures: {png_bad}")
    # Browser audit must be genuinely clean.
    browser=json.loads((ROOT/"browser_audit.json").read_text(encoding="utf-8"))
    bfail=[]
    for slug,entry in browser["cards"].items():
        for mode in ["desktop","mobile"]:
            d=entry[mode]
            if d["mathjax_containers"]<1 or d["horizontal_overflow"] or d["overflow_boxes"] or d["console"] or d["page_errors"]: bfail.append(f"{slug}:{mode}")
    if browser["asset_resolution"]["failures"]: bfail.append("asset resolution")
    if browser["landing"]["desktop"]["tile_count"]!=5 or browser["landing"]["mobile"]["tile_count"]!=5 or browser["landing"]["desktop"]["horizontal_overflow"] or browser["landing"]["mobile"]["horizontal_overflow"]: bfail.append("landing")
    add("browser_desktop_mobile_mathjax_overflow",not bfail,"all cards + landing clean" if not bfail else ", ".join(bfail))
    passed=all(c["passed"] for c in checks)
    report=["# Deterministic self-QA — Harry P3 October 2025 + ESAT multi-step v2","","**Scope:** local-only build under `multistep_v2/`; five cards (ESAT + P3 Q2–Q5), landing page, diagrams, static PNG exports.","","**Status:** `PASS`" if passed else "**Status:** `FAIL`","","This is builder-run deterministic self-QA. It is **not** an independent card review, and no publication has been performed.","","## Checks"]
    report += [f"- [{'PASS' if c['passed'] else 'FAIL'}] **{c['name']}** — {c['detail']}" for c in checks]
    report += ["","## Scope and source boundary","- Guide provenance is the SHA-256 recorded in `build_manifest.json` for the passed final 11 July guide.","- P3 Q1 is omitted rather than reconstructed from legacy material: the passed guide says it was discussed only and does not retain a complete verbatim standalone prompt. P3 Q6–Q9 were not discussed.","- `independent_review.status = not_recorded`; `publication.status = local_only`."]
    (ROOT/"qa_report.md").write_text("\n".join(report)+"\n",encoding="utf-8")
    # Hash final output except this manifest (self-reference impossible). qa_report is included.
    final_files=[p for p in ROOT.rglob("*") if p.is_file() and p.name!="build_manifest.json"]
    manifest={"artifact":"Harry P3 Oct 2025 + ESAT multi-step deck v2","source_freeze_date":"2026-07-11","guide_provenance":{"path":str(GUIDE),"sha256":sha(GUIDE)},"scope":{"cards":CARDS,"omitted":{"P3_Oct2025_Q1":"discussed only; passed guide does not preserve a complete verbatim standalone prompt","P3_Oct2025_Q6_to_Q9":"not discussed in the lesson"}},"status":{"deterministic_self_qa":"pass" if passed else "fail","independent_review":{"status":"not_recorded","pass_claimed":False},"publication":{"status":"local_only"}},"manifest_self_hash":"omitted: self-reference","files":[{"path":str(p.relative_to(ROOT)),"bytes":p.stat().st_size,"sha256":sha(p)} for p in sorted(final_files)]}
    (ROOT/"build_manifest.json").write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"pass":passed,"checks":len(checks),"manifest_sha256":sha(ROOT/"build_manifest.json")},indent=2))
    if not passed: raise SystemExit(1)
if __name__=="__main__": main()
